import { useState } from 'react';
import { useApp } from '../../contexts/AppContext';

function loadJSON(key, fallback) {
  try { const s = localStorage.getItem(key); return s ? JSON.parse(s) : fallback; } catch { return fallback; }
}

import {
  Settings, Building2, Key, Shield, Clock, Users, Globe, Mail,
  Save, AlertTriangle, CheckCircle2, ChevronRight, Trash2, FileText,
  Lock, Eye, UserCheck, Download, Plus, X, UserPlus
} from 'lucide-react';

const PRIVACY_POLICY = `PHISHGUARD AI — EMPLOYEE PRIVACY POLICY TEMPLATE\n\n1. PURPOSE\nThis policy outlines how [Company Name] uses PhishGuard AI for security awareness training.\n\n2. SCOPE\nAll employees are subject to periodic phishing simulation exercises.\n\n3. DATA COLLECTION\n- Simulation interaction data (open, click, report)\n- Training completion records\n- Risk scores (anonymized for reporting)\n\n4. DATA USE\n- Training improvement ONLY\n- Never used for performance reviews or disciplinary action\n- Aggregated for compliance reporting\n\n5. EMPLOYEE RIGHTS\n- Right to view your own training history\n- Right to request data deletion\n- Right to opt-out with manager approval\n\n6. RETENTION\nSimulation data is auto-purged after 12 months.\n\nGenerated by PhishGuard AI`;

const COMM_TEMPLATE = `Subject: Security Awareness Training Program — What to Expect\n\nDear Team,\n\nAs part of our commitment to cybersecurity, we are implementing PhishGuard AI — an AI-powered security awareness platform.\n\nWhat this means for you:\n- You may receive simulated phishing emails as part of training\n- If you click a simulation link, you'll see a friendly educational page\n- This is NOT a test — there are no penalties\n- Your participation helps strengthen our security posture\n\nKey points:\n✓ No disciplinary action will result from simulations\n✓ Results are anonymized in company reports\n✓ You can view your own progress in the Training Portal\n✓ Report suspicious emails using the Report Phishing button\n\nQuestions? Contact the IT Security team.\n\nBest regards,\n[IT Security Team]`;

function downloadText(filename, content) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

const tabs = [
  { id: 'org', label: 'Organization', icon: Building2 },
  { id: 'clients', label: 'Client Companies', icon: Users },
  { id: 'api', label: 'API & Integrations', icon: Key },
  { id: 'email', label: 'Email Configuration', icon: Mail },
  { id: 'compliance', label: 'Compliance & Privacy', icon: Shield },
  { id: 'audit', label: 'Audit Log', icon: FileText },
];

const AUDIT_LOG = [
  { time: '2026-04-28 17:05', user: 'Admin', action: 'Campaign approved', detail: 'Q2 Vendor Payment Update campaign deployed', severity: 'info' },
  { time: '2026-04-28 15:30', user: 'Admin', action: 'Campaign created', detail: 'AI-generated "CEO Town Hall Invite" saved as draft', severity: 'info' },
  { time: '2026-04-27 11:15', user: 'Admin', action: 'Bulk employee import', detail: '12 employees added to Engineering', severity: 'success' },
  { time: '2026-04-26 09:00', user: 'System', action: 'Risk score spike', detail: 'Aisha Patel risk: 79 → 88 after click', severity: 'critical' },
  { time: '2026-04-25 14:20', user: 'Admin', action: 'Settings modified', detail: 'Max 2 simulations/employee/week', severity: 'info' },
  { time: '2026-04-24 10:45', user: 'System', action: 'Campaign completed', detail: 'Benefits Open Enrollment — 26% click rate', severity: 'warning' },
  { time: '2026-04-23 16:30', user: 'Admin', action: 'API key rotated', detail: 'OpenRouter API key rotated', severity: 'success' },
  { time: '2026-04-22 08:00', user: 'System', action: 'Training auto-assigned', detail: '"Recognizing BEC Attacks" → 5 employees', severity: 'info' },
  { time: '2026-04-21 13:10', user: 'Admin', action: 'Department added', detail: 'Cybersecurity department created', severity: 'info' },
  { time: '2026-04-20 09:30', user: 'System', action: 'Compliance check passed', detail: 'SOC 2 Type II auto-validation OK', severity: 'success' },
  { time: '2026-04-19 16:45', user: 'Admin', action: 'Client company added', detail: 'NorthStar Financial onboarded', severity: 'success' },
  { time: '2026-04-18 11:00', user: 'System', action: 'Data purge executed', detail: '14 records auto-deleted (12-month retention)', severity: 'warning' },
];

export default function SettingsPage() {
  const { selectedOrg, apiSettings, setApiSettings, organizations, addCompany, removeCompany, addEmployee, employees, getDepartments, setDepartments, updateCompany } = useApp();
  const [activeTab, setActiveTab] = useState('org');
  const [saved, setSaved] = useState(false);
  const [depts, setDeptsLocal] = useState(() => getDepartments(selectedOrg.id));
  const [newDept, setNewDept] = useState('');
  const [showAddDept, setShowAddDept] = useState(false);
  const [apiKey, setApiKey] = useState(apiSettings.apiKey);
  const [apiModel, setApiModel] = useState(apiSettings.model);
  const [showAddCo, setShowAddCo] = useState(false);
  const [newCo, setNewCo] = useState({ name: '', industry: 'Technology', logo: '🏢' });
  const [showAddEmp, setShowAddEmp] = useState(null);
  const [newEmp, setNewEmp] = useState({ name: '', dept: '', email: '' });
  const [blackouts, setBlackouts] = useState(() => loadJSON('pg-blackouts', { weekends: true, after6: true, holidays: false, quarterly: false }));
  const [privacyToggles, setPrivacyToggles] = useState(() => loadJSON('pg-privacy', { encrypt: true, anonymize: true, autopurge: true, visible: false, managerOnly: true }));
  const [emailDomain, setEmailDomain] = useState(() => loadJSON('pg-email-domain', 'simulations@phishguard-training.com'));
  const [maxSims, setMaxSims] = useState(() => loadJSON('pg-max-sims', 2));
  const auditLogs = AUDIT_LOG;

  function handleSave() {
    setSaved(true);
    setTimeout(() => setSaved(false), 2000);
  }
  function handleAddDept() {
    if (!newDept.trim()) return;
    const updated = [...depts, newDept.trim()];
    setDeptsLocal(updated);
    setDepartments(selectedOrg.id, updated);
    setNewDept(''); setShowAddDept(false); handleSave();
  }
  function handleRemoveDept(d) {
    const updated = depts.filter(x => x !== d);
    setDeptsLocal(updated);
    setDepartments(selectedOrg.id, updated);
  }
  function handleSaveApi() {
    setApiSettings({ apiKey, model: apiModel });
    handleSave();
  }
  function handleAddCompany() {
    if (!newCo.name.trim()) return;
    addCompany(newCo);
    setNewCo({ name: '', industry: 'Technology', logo: '🏢' });
    setShowAddCo(false); handleSave();
  }
  function handleAddEmployee(orgId) {
    if (!newEmp.name.trim()) return;
    addEmployee(orgId, newEmp);
    setNewEmp({ name: '', dept: '', email: '' });
    setShowAddEmp(null); handleSave();
  }

  return (
    <section className="space-y-6 animate-fade-in-up">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
          <Settings className="w-6 h-6 text-accent-500" /> Settings
        </h1>
        <p className="text-sm text-slate-500 mt-1">Manage your organization, integrations, and compliance settings.</p>
      </div>

      <div className="flex gap-6">
        {/* Tab Nav */}
        <div className="w-56 shrink-0 space-y-1">
          {tabs.map(({ id, label, icon: Icon }) => (
            <button key={id} onClick={() => setActiveTab(id)}
              className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all cursor-pointer ${activeTab === id ? 'bg-accent-500/10 text-accent-500' : 'text-slate-500 hover:bg-black/5 hover:text-slate-700'}`}>
              <Icon className="w-4 h-4" /> {label}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="flex-1">
          {activeTab === 'org' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <h2 className="text-lg font-semibold text-slate-800">Organization Profile</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Company Name</label>
                  <input type="text" defaultValue={selectedOrg.name} className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Industry</label>
                  <input type="text" defaultValue={selectedOrg.industry} className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Primary Contact Email</label>
                  <input type="email" defaultValue="admin@greenfield.com" className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Subscription Tier</label>
                  <div className="bg-accent-500/8 border border-accent-500/15 rounded-xl px-4 py-2.5 text-sm text-accent-500 font-semibold">Enterprise Plan</div>
                </div>
              </div>

              <h3 className="text-sm font-semibold text-slate-800 mt-4 pt-4 border-t border-black/5">Departments</h3>
              <div className="flex flex-wrap gap-2">
                {depts.map(d => (
                  <span key={d} className="text-xs bg-slate-50 px-3 py-1.5 rounded-lg border border-black/5 text-slate-600 flex items-center gap-1.5">
                    {d} <button onClick={() => handleRemoveDept(d)} className="text-slate-300 hover:text-risk-500 cursor-pointer"><Trash2 className="w-3 h-3" /></button>
                  </span>
                ))}
                {showAddDept ? (
                  <div className="flex items-center gap-1.5">
                    <input type="text" value={newDept} onChange={e => setNewDept(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleAddDept()} placeholder="Dept name" autoFocus className="text-xs bg-white border border-accent-500/30 rounded-lg px-2 py-1.5 w-28 outline-none" />
                    <button onClick={handleAddDept} className="text-accent-500 cursor-pointer"><CheckCircle2 className="w-4 h-4" /></button>
                    <button onClick={() => setShowAddDept(false)} className="text-slate-400 cursor-pointer"><X className="w-4 h-4" /></button>
                  </div>
                ) : (
                  <button onClick={() => setShowAddDept(true)} className="text-xs text-accent-500 bg-accent-500/8 px-3 py-1.5 rounded-lg border border-accent-500/15 cursor-pointer hover:bg-accent-500/15 transition-colors">+ Add</button>
                )}
              </div>

              <button onClick={handleSave} className="flex items-center gap-2 bg-gradient-to-r from-accent-500 to-accent-400 text-white font-semibold text-sm py-2.5 px-5 rounded-xl transition-all shadow-lg shadow-accent-500/25 cursor-pointer mt-4">
                {saved ? <><CheckCircle2 className="w-4 h-4" /> Saved!</> : <><Save className="w-4 h-4" /> Save Changes</>}
              </button>
            </div>
          )}

          {activeTab === 'api' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <h2 className="text-lg font-semibold text-slate-800">API & Integration Settings</h2>

              <div className="space-y-4">
                <div className="bg-slate-50 rounded-xl p-4 border border-black/5 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-lg bg-accent-500/10 flex items-center justify-center"><Key className="w-4 h-4 text-accent-500" /></div>
                      <div>
                        <p className="text-sm font-semibold text-slate-800">OpenRouter API</p>
                        <p className="text-[10px] text-slate-400">AI-powered phishing email generation</p>
                      </div>
                    </div>
                    <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full ${apiKey ? 'text-secure-500 bg-secure-500/10' : 'text-warn-500 bg-warn-500/10'}`}>
                      {apiKey ? '● Connected' : '○ Not configured'}
                    </span>
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-medium uppercase tracking-wider text-slate-400">API Key</label>
                    <input type="password" value={apiKey} onChange={e => setApiKey(e.target.value)} placeholder="sk-or-v1-..." className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all font-mono" />
                  </div>
                  <div className="space-y-1.5">
                    <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Model</label>
                    <input type="text" value={apiModel} onChange={e => setApiModel(e.target.value)} className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all font-mono" />
                  </div>
                </div>

                <div className="bg-slate-50 rounded-xl p-4 border border-black/5">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-lg bg-slate-200 flex items-center justify-center"><Mail className="w-4 h-4 text-slate-500" /></div>
                      <div>
                        <p className="text-sm font-semibold text-slate-800">SendGrid Email API</p>
                        <p className="text-[10px] text-slate-400">Programmatic email delivery for campaigns</p>
                      </div>
                    </div>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full text-slate-400 bg-slate-100">○ Phase 3</span>
                  </div>
                </div>

                <div className="bg-slate-50 rounded-xl p-4 border border-black/5">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="w-8 h-8 rounded-lg bg-slate-200 flex items-center justify-center"><Globe className="w-4 h-4 text-slate-500" /></div>
                      <div>
                        <p className="text-sm font-semibold text-slate-800">Microsoft 365 / Google Workspace</p>
                        <p className="text-[10px] text-slate-400">Employee directory sync & SSO</p>
                      </div>
                    </div>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full text-slate-400 bg-slate-100">○ Phase 3</span>
                  </div>
                </div>
              </div>

              <button onClick={handleSaveApi} className="flex items-center gap-2 bg-gradient-to-r from-accent-500 to-accent-400 text-white font-semibold text-sm py-2.5 px-5 rounded-xl transition-all shadow-lg shadow-accent-500/25 cursor-pointer">
                {saved ? <><CheckCircle2 className="w-4 h-4" /> Saved!</> : <><Save className="w-4 h-4" /> Save Configuration</>}
              </button>
            </div>
          )}

          {activeTab === 'email' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <h2 className="text-lg font-semibold text-slate-800">Email Configuration</h2>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Sending Domain</label>
                  <input type="text" value={emailDomain} onChange={e => setEmailDomain(e.target.value)} className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-medium uppercase tracking-wider text-slate-400">Max Simulations / Employee / Week</label>
                  <input type="number" value={maxSims} onChange={e => setMaxSims(Number(e.target.value))} className="w-full bg-white border border-black/10 rounded-xl px-4 py-2.5 text-sm text-slate-800 focus:outline-none focus:ring-2 focus:ring-accent-500/30 transition-all" />
                </div>
              </div>

              <h3 className="text-sm font-semibold text-slate-800 pt-4 border-t border-black/5">Sending Schedule Blackout</h3>
              <p className="text-[11px] text-slate-400 -mt-2">No simulations will be sent during these windows</p>
              <div className="space-y-2">
                {[
                  { key: 'weekends', label: 'Weekends' },
                  { key: 'after6', label: 'After 6:00 PM' },
                  { key: 'holidays', label: 'Company holidays' },
                  { key: 'quarterly', label: 'Quarterly close periods' },
                ].map((b) => (
                  <label key={b.key} onClick={() => { const u = { ...blackouts, [b.key]: !blackouts[b.key] }; setBlackouts(u); localStorage.setItem('pg-blackouts', JSON.stringify(u)); }} className="flex items-center justify-between py-2 px-3 rounded-lg bg-slate-50 border border-black/5 cursor-pointer">
                    <span className="text-sm text-slate-600">{b.label}</span>
                    <div className={`w-10 h-6 rounded-full transition-all ${blackouts[b.key] ? 'bg-accent-500' : 'bg-slate-200'} relative cursor-pointer`}>
                      <div className={`absolute top-1 w-4 h-4 rounded-full bg-white shadow transition-all ${blackouts[b.key] ? 'left-5' : 'left-1'}`} />
                    </div>
                  </label>
                ))}
              </div>

              <button onClick={() => { localStorage.setItem('pg-email-domain', JSON.stringify(emailDomain)); localStorage.setItem('pg-max-sims', JSON.stringify(maxSims)); handleSave(); }} className="flex items-center gap-2 bg-gradient-to-r from-accent-500 to-accent-400 text-white font-semibold text-sm py-2.5 px-5 rounded-xl transition-all shadow-lg shadow-accent-500/25 cursor-pointer">
                {saved ? <><CheckCircle2 className="w-4 h-4" /> Saved!</> : <><Save className="w-4 h-4" /> Save Configuration</>}
              </button>
            </div>
          )}

          {activeTab === 'audit' && (
            <div className="glass rounded-2xl overflow-hidden animate-fade-in-up">
              <div className="px-6 py-4 border-b border-black/5 flex items-center justify-between">
                <h2 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                  <Shield className="w-5 h-5 text-accent-500" /> Audit Log
                </h2>
                <span className="text-[10px] text-slate-400 uppercase tracking-wider">GDPR / SOC2 Compliant</span>
              </div>
              <div className="divide-y divide-black/[.04]">
                {AUDIT_LOG.map((log, i) => {
                  const typeColors = { campaign: 'bg-accent-500/10 text-accent-500', employee: 'bg-warn-500/10 text-warn-500', risk: 'bg-risk-500/10 text-risk-500', settings: 'bg-slate-100 text-slate-500', training: 'bg-secure-500/10 text-secure-500' };
                  return (
                    <div key={i} className="px-6 py-3 flex items-start gap-3 hover:bg-accent-500/[.02] transition-colors">
                      <div className={`text-[9px] font-semibold px-2 py-0.5 rounded-full mt-1 shrink-0 ${typeColors[log.type]}`}>{log.type}</div>
                      <div className="flex-1">
                        <p className="text-sm text-slate-700">{log.action}</p>
                        <p className="text-xs text-slate-400 mt-0.5">{log.detail}</p>
                      </div>
                      <div className="text-right shrink-0">
                        <p className="text-[10px] text-slate-400">{log.time}</p>
                        <p className="text-[10px] text-slate-300">{log.user}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {activeTab === 'compliance' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <h2 className="text-lg font-semibold text-slate-800">Compliance & Privacy</h2>

              <div className="space-y-3">
                <h3 className="text-sm font-semibold text-slate-800 flex items-center gap-2"><Shield className="w-4 h-4 text-accent-500" /> Framework Compliance</h3>
                {[
                  { framework: 'SOC 2 Type II', control: 'CC6.1 — Security Awareness', status: 'Compliant', lastAudit: '2026-03-15', next: '2026-09-15' },
                  { framework: 'NIST CSF', control: 'PR.AT-1 — Awareness Training', status: 'Compliant', lastAudit: '2026-02-20', next: '2026-08-20' },
                  { framework: 'ISO 27001', control: 'A.7.2.2 — Information Security Awareness', status: 'In Progress', lastAudit: '—', next: '2026-06-01' },
                  { framework: 'GDPR', control: 'Art. 39 — DPO Awareness Duties', status: 'Compliant', lastAudit: '2026-01-10', next: '2027-01-10' },
                  { framework: 'HIPAA', control: '164.308(a)(5) — Security Awareness', status: 'N/A', lastAudit: '—', next: '—' },
                ].map((c, i) => (
                  <div key={i} className="bg-slate-50 rounded-xl p-4 border border-black/5 flex items-center justify-between flex-wrap gap-2">
                    <div className="flex-1 min-w-[200px]">
                      <p className="text-sm font-semibold text-slate-800">{c.framework}</p>
                      <p className="text-[11px] text-slate-400">{c.control}</p>
                    </div>
                    <div className="text-right text-xs">
                      <p className="text-slate-400">Last: {c.lastAudit} · Next: {c.next}</p>
                    </div>
                    <span className={`text-[10px] font-semibold px-2.5 py-1 rounded-full ${c.status === 'Compliant' ? 'text-secure-500 bg-secure-500/10' : c.status === 'In Progress' ? 'text-warn-500 bg-warn-500/10' : 'text-slate-400 bg-slate-100'}`}>{c.status}</span>
                  </div>
                ))}
              </div>

              <div className="pt-4 border-t border-black/5 space-y-3">
                <h3 className="text-sm font-semibold text-slate-800 flex items-center gap-2"><Lock className="w-4 h-4 text-accent-500" /> Data Privacy Controls</h3>
                {[
                  { key: 'encrypt', label: 'Employee data encrypted at rest (AES-256)' },
                  { key: 'anonymize', label: 'Simulation results anonymized in reports' },
                  { key: 'autopurge', label: 'Employee click data auto-purged after 12 months' },
                  { key: 'visible', label: 'Individual risk scores visible to employees' },
                  { key: 'managerOnly', label: 'Manager access to direct reports only' },
                ].map((p) => (
                  <label key={p.key} onClick={() => { const u = { ...privacyToggles, [p.key]: !privacyToggles[p.key] }; setPrivacyToggles(u); localStorage.setItem('pg-privacy', JSON.stringify(u)); }} className="flex items-center justify-between py-2 px-3 rounded-lg bg-slate-50 border border-black/5 cursor-pointer">
                    <span className="text-sm text-slate-600">{p.label}</span>
                    <div className={`w-10 h-6 rounded-full transition-all ${privacyToggles[p.key] ? 'bg-secure-500' : 'bg-slate-200'} relative cursor-pointer`}>
                      <div className={`absolute top-1 w-4 h-4 rounded-full bg-white shadow transition-all ${privacyToggles[p.key] ? 'left-5' : 'left-1'}`} />
                    </div>
                  </label>
                ))}
              </div>

              <div className="pt-4 border-t border-black/5 space-y-3">
                <h3 className="text-sm font-semibold text-slate-800 flex items-center gap-2"><UserCheck className="w-4 h-4 text-accent-500" /> Employee Rights</h3>
                <div className="bg-accent-500/5 rounded-xl p-4 border border-accent-500/10">
                  <p className="text-sm text-slate-600 leading-relaxed">PhishGuard AI is designed with a <span className="text-accent-500 font-medium">no-blame, positive-reinforcement</span> philosophy. Simulation results are used exclusively for training improvement and are never tied to performance reviews, disciplinary action, or termination decisions.</p>
                </div>
                <div className="flex gap-3">
                  <button onClick={() => downloadText('PhishGuard_Privacy_Policy.txt', PRIVACY_POLICY)} className="flex items-center gap-1.5 text-xs font-medium text-accent-500 bg-accent-500/8 px-3 py-2 rounded-lg border border-accent-500/15 cursor-pointer hover:bg-accent-500/15 transition-all">
                    <Download className="w-3.5 h-3.5" /> Download Privacy Policy Template
                  </button>
                  <button onClick={() => downloadText('PhishGuard_Employee_Communication.txt', COMM_TEMPLATE)} className="flex items-center gap-1.5 text-xs font-medium text-accent-500 bg-accent-500/8 px-3 py-2 rounded-lg border border-accent-500/15 cursor-pointer hover:bg-accent-500/15 transition-all">
                    <Eye className="w-3.5 h-3.5" /> Download Employee Communication Template
                  </button>
                </div>
              </div>
            </div>
          )}

          {activeTab === 'clients' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <div className="flex items-center justify-between">
                <h2 className="text-lg font-semibold text-slate-800">Client Companies</h2>
                <button onClick={() => setShowAddCo(true)} className="flex items-center gap-1.5 text-xs font-medium text-white bg-gradient-to-r from-accent-500 to-accent-400 px-3 py-2 rounded-lg cursor-pointer"><Plus className="w-3.5 h-3.5" /> Add Client</button>
              </div>
              {showAddCo && (
                <div className="bg-accent-500/5 rounded-xl p-4 border border-accent-500/10 space-y-3 animate-slide-down">
                  <div className="grid grid-cols-3 gap-3">
                    <input type="text" value={newCo.name} onChange={e => setNewCo({...newCo, name: e.target.value})} placeholder="Company name" className="col-span-2 bg-white border border-black/10 rounded-lg px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-accent-500/30" />
                    <select value={newCo.industry} onChange={e => setNewCo({...newCo, industry: e.target.value})} className="bg-white border border-black/10 rounded-lg px-3 py-2 text-sm outline-none">
                      {['Technology','Healthcare','Financial Services','Manufacturing','Retail','Education'].map(i => <option key={i}>{i}</option>)}
                    </select>
                  </div>
                  <div className="flex gap-2">
                    <button onClick={handleAddCompany} className="text-xs font-medium text-white bg-accent-500 px-3 py-1.5 rounded-lg cursor-pointer">Add Company</button>
                    <button onClick={() => setShowAddCo(false)} className="text-xs text-slate-400 cursor-pointer">Cancel</button>
                  </div>
                </div>
              )}
              <div className="space-y-3">
                {organizations.map(org => {
                  const staff = employees[org.id] || [];
                  return (
                    <div key={org.id} className="bg-slate-50 rounded-xl p-4 border border-black/5">
                      <div className="flex items-center justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <span className="text-lg">{org.logo}</span>
                          <div><p className="text-sm font-semibold text-slate-800">{org.name}</p><p className="text-[10px] text-slate-400">{org.industry} · {staff.length} employees</p></div>
                        </div>
                        <div className="flex items-center gap-2">
                          <button onClick={() => setShowAddEmp(showAddEmp === org.id ? null : org.id)} className="text-[10px] text-accent-500 bg-accent-500/8 px-2 py-1 rounded-md cursor-pointer hover:bg-accent-500/15"><UserPlus className="w-3 h-3 inline mr-1" />Add Employee</button>
                          {organizations.length > 1 && <button onClick={() => removeCompany(org.id)} className="text-slate-300 hover:text-risk-500 cursor-pointer"><Trash2 className="w-3.5 h-3.5" /></button>}
                        </div>
                      </div>
                      {showAddEmp === org.id && (
                        <div className="bg-white rounded-lg p-3 border border-accent-500/10 mt-2 space-y-2 animate-slide-down">
                          <div className="grid grid-cols-3 gap-2">
                            <input type="text" value={newEmp.name} onChange={e => setNewEmp({...newEmp, name: e.target.value})} placeholder="Full name" className="bg-slate-50 border border-black/10 rounded-lg px-2 py-1.5 text-xs outline-none" />
                            <input type="text" value={newEmp.dept} onChange={e => setNewEmp({...newEmp, dept: e.target.value})} placeholder="Department" className="bg-slate-50 border border-black/10 rounded-lg px-2 py-1.5 text-xs outline-none" />
                            <button onClick={() => handleAddEmployee(org.id)} className="text-xs text-white bg-accent-500 rounded-lg cursor-pointer">Add</button>
                          </div>
                        </div>
                      )}
                      {staff.length > 0 && (
                        <div className="mt-2 flex flex-wrap gap-1">
                          {staff.slice(0, 6).map(e => <span key={e.id} className="text-[10px] bg-white px-2 py-0.5 rounded-md border border-black/5 text-slate-500">{e.name}</span>)}
                          {staff.length > 6 && <span className="text-[10px] text-slate-400 px-2 py-0.5">+{staff.length - 6} more</span>}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {activeTab === 'audit' && (
            <div className="glass rounded-2xl p-6 space-y-5 animate-fade-in-up">
              <div className="flex items-center justify-between">
                <div>
                  <h2 className="text-lg font-semibold text-slate-800">Audit Log</h2>
                  <p className="text-[11px] text-slate-400 mt-0.5">Complete activity trail for compliance and security review</p>
                </div>
                <button onClick={() => {
                  const rows = ['Timestamp,User,Action,Details,Severity'];
                  auditLogs.forEach(l => rows.push(`${l.time},${l.user},"${l.action}","${l.detail}",${l.severity}`));
                  const blob = new Blob([rows.join('\n')], { type: 'text/csv' });
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement('a'); a.href = url; a.download = 'phishguard_audit_log.csv'; a.click();
                  URL.revokeObjectURL(url);
                }} className="flex items-center gap-1.5 text-xs font-medium text-accent-500 bg-accent-500/8 px-3 py-2 rounded-lg border border-accent-500/15 hover:bg-accent-500/15 transition-all cursor-pointer">
                  <Download className="w-3.5 h-3.5" /> Export Log
                </button>
              </div>

              <div className="space-y-1">
                {auditLogs.map((log, i) => (
                  <div key={i} className="flex items-center gap-3 py-2.5 px-3 rounded-lg hover:bg-slate-50 transition-colors animate-fade-in-up" style={{ animationDelay: `${0.03 * i}s` }}>
                    <div className={`w-2 h-2 rounded-full shrink-0 ${log.severity === 'critical' ? 'bg-risk-500' : log.severity === 'warning' ? 'bg-warn-500' : log.severity === 'success' ? 'bg-secure-500' : 'bg-slate-300'}`} />
                    <span className="text-[10px] text-slate-400 font-mono w-36 shrink-0">{log.time}</span>
                    <span className="text-xs font-medium text-slate-700 w-32 shrink-0">{log.user}</span>
                    <span className="text-xs text-slate-600 flex-1">{log.action}</span>
                    <span className="text-[10px] text-slate-400 hidden md:inline">{log.detail}</span>
                    <span className={`text-[9px] font-semibold px-2 py-0.5 rounded-full shrink-0 ${log.severity === 'critical' ? 'text-risk-500 bg-risk-500/10' : log.severity === 'warning' ? 'text-warn-500 bg-warn-500/10' : log.severity === 'success' ? 'text-secure-500 bg-secure-500/10' : 'text-slate-400 bg-slate-100'}`}>{log.severity}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
